[store]
dir = "./target/nextest"

# This section defines the default nextest profile. Custom profiles are layered
# on top of the default profile.
[profile.default]
test-threads = "num-cpus"
threads-required = 1

# Show these test statuses in the output.
#
# The possible values this can take are:
# * none: no output
# * fail: show failed (including exec-failed) tests
# * retry: show flaky and retried tests
# * slow: show slow tests
# * pass: show passed tests
# * skip: show skipped tests (most useful for CI)
# * all: all of the above
#
# Each value includes all the values above it; for example, "slow" includes
# failed and retried tests.
#
# Can be overridden through the `--status-level` flag.
status-level = "pass"
final-status-level = "flaky"
fail-fast = false
slow-timeout = { period = "6s", terminate-after = 2 }

[profile.default.junit]
path = "result.xml"
report-name = "nextest-run"
store-success-output = true
store-failure-output = true
